### PR TITLE
Feat/gpio: Add basic GPIO support

### PR DESCRIPTION
**Pull request by DhruvaG2000**
Implements functions:
* ``pinMode()``
* ``digitalWrite()``

Example:
includes a working and tested blinky example that blinks on board LED.

### CODE REVIEW

**Comment by alvarowolfx** [comment]
I feel like is relatively lowkey to also add implementation for the `digitalRead` method using Zephyr under the hood, especially since the `pinMode` method is allowing to set the pin as `INPUT`. Zephyr has `gpio_pin_get` that can be used for that.

https://docs.zephyrproject.org/latest/hardware/peripherals/gpio.html#c.gpio_pin_get

**Comment by DhruvaG2000** [comment]
> I feel like is relatively lowkey to also add implementation for the `digitalRead` method using Zephyr under the hood, especially since the `pinMode` method is allowing to set the pin as `INPUT`. Zephyr has `gpio_pin_get` that can be used for that.
> 
> https://docs.zephyrproject.org/latest/hardware/peripherals/gpio.html#c.gpio_pin_get

Thanks for the suggestion, will try this right away

**Comment by DhruvaG2000** [comment]
@alvarowolfx Please review again, Tested code using following example:
```c++
#include <ArduinoAPI.h>

/* 1000 msec = 1 sec */
#define SLEEP_TIME_MS 1000

const int buttonPin = D9;     // the number of the pushbutton pin
const int ledPin =  13;      // the number of the LED pin

// variables will change:
int buttonState = 0;         // variable for reading the pushbutton status

void setup() {
  // initialize the LED pin as an output:
  
  // initialize the pushbutton pin as an input:
  pinMode(buttonPin, INPUT);
  pinMode(ledPin, OUTPUT);
}

void loop() {
  // read the state of the pushbutton value:
  buttonState = digitalRead(buttonPin);

//   // check if the pushbutton is pressed. If it is, the buttonState is HIGH:
  if (buttonState == HIGH) {
    // turn LED on:
    digitalWrite(ledPin, HIGH);
  } else {
    // turn LED off:
    digitalWrite(ledPin, LOW);
  }
}
```

Thus verified GPIO ``read``, ``write`` and `pinMode`

**Comment by alvarowolfx** [comment]
Awesome, this PR looks good to me, I think you can merge it.

**Pull request merged**
